/**
 * Spotlight.js v0.4.0 (CDN)
 * Copyright 2019 Nextapps GmbH
 * Author: Thomas Wilkerling
 * Licence: Apache-2.0
 * https://github.com/nextapps-de/spotlight
 */(function(){'use strict';var aa={};function ba(a){for(var b=a.classList,c={},d=0;d<b.length;d++)c[b[d]]=1;a.a=c}function g(a,b){a=ca(a);"string"===typeof b&&(b=[b]);for(var c=0;c<b.length;c++)for(var d=b[c],f=0;f<a.length;f++){var e=a[f];e.a||ba(e);e.a[d]||(e.a[d]=1,e.classList.add(d))}}function h(a,b){a=ca(a);"string"===typeof b&&(b=[b]);for(var c=0;c<b.length;c++)for(var d=b[c],f=0;f<a.length;f++){var e=a[f];e.a||ba(e);e.a[d]&&(e.a[d]=0,e.classList.remove(d))}}
function k(a,b,c,d){a=ca(a);if("string"===typeof b)for(var f=0;f<a.length;f++){var e=a[f],m=e.b;m||(e.b=m={});m[b]!==c&&(m[b]=c,e.style.setProperty(aa[b]||(aa[b]=b.replace(/([a-z])([A-Z])/g,"$1-$2").toLowerCase()),c,d||null))}else for(f=Object.keys(b),e=0;e<f.length;e++){m=f[e];c=b[m];for(var n=0;n<a.length;n++)k(a[n],m,c,d)}}var da=0;function ea(a,b,c){k(a,"transition","none");k(a,b,c);da||(da=a.clientTop&&0);k(a,"transition","")}
function ca(a){if(a.constructor===Array){for(var b=0;b<a.length;b++){var c=a[b];a[b]="string"===typeof c?document.querySelector(c):c}return a}return"string"===typeof a?document.querySelectorAll(a):[a]}function l(a,b){return(b||document).getElementsByClassName(a)};function fa(a,b,c,d){ha("add",a,b,c,d)}function ia(a,b,c,d){ha("remove",a,b,c,d)}function ha(a,b,c,d,f){b[a+"EventListener"](c||"click",d,"undefined"===typeof f?!0:f)}function p(a,b){a||(a=window.event);a&&(b||a.preventDefault(),a.stopImmediatePropagation(),a.returnValue=!1);return!1};var ja=document.createElement("link");ja.rel="stylesheet";ja.href="https://rawcdn.githack.com/nextapps-de/spotlight/master/dist/css/spotlight.css";document.getElementsByTagName("head")[0].appendChild(ja);var q="theme fullscreen autofit zoom-in zoom-out page title description player".split(" "),r,t,ka,la,u,v,w,x,y,ma=!1,na=!1,z=!1,A=!1,B=!1,D=!1,E,F,G,H,I,J,K,L,M,N,oa,pa,qa,ra,O,sa,P,Q=null,R=null,S=null,T,ta;
function ua(a,b){if(F=a.length){K||(K=l("pane",M));for(var c=K.length,d=G.title,f=G.description,e=0;e<F;e++){var m=a[e];if(e<c)var n=K[e];else n=K[0].cloneNode(!0),k(n,"left",100*e+"%"),K[0].parentNode.appendChild(n);var C=void 0;n=n.dataset;n.src=m.href||m.src;var W=m.dataset;"false"!==d&&(n.title=m.title||W&&W.title||(C=(m||document).getElementsByTagName("img")).length&&C[0].alt||d||"");"false"!==f&&(n.description=m.description||W&&W.description||f||"")}ea(I,"transform","translateX(-"+100*((b||
1)-1)+"%)");va(b||1);U()}}
function wa(a,b){G={};b&&xa(b);xa(a);a.description&&(G.description=b?b.description:!1);a.title&&(G.title=b?b.title:!1);H=G.infinite;"undefined"!==typeof G.zoom&&(G["zoom-in"]=G["zoom-out"]=G.zoom,delete G.zoom);if("undefined"!==typeof G.control){a=G.control.split(",");for(b=0;b<q.length;b++)G[q[b]]="false";for(b=0;b<a.length;b++){var c=a[b].trim();"zoom"===c?G["zoom-in"]=G["zoom-out"]="true":G[c]="true"}}for(a=0;a<q.length;a++)b=q[a],k(l(b,M)[0],"display","false"===G[b]?"none":"table-cell");"undefined"===
typeof D&&(D=G.theme,"white"===D&&ya())}function xa(a){for(var b=G,c=Object.keys(a),d=0;d<c.length;d++){var f=c[d];b[f]=""+a[f]}}function va(a){J=K[a-1];L=J.firstElementChild;E=a;return L?!0:(g(M,"loading"),L=new Image,L.onload=function(){h(M,"loading");k(this,{visibility:"visible",opacity:1,transform:""})},L.onerror=function(){J.removeChild(L)},J.appendChild(L),L.src=J.dataset.src,!1)}
fa(document,"DOMContentLoaded",function(){M=document.createElement("div");M.id="spotlight";M.innerHTML='<div class=preloader style="background-image:url(https://rawcdn.githack.com/nextapps-de/spotlight/master/dist/img/preloader.svg)"></div><div class=scene><div class=pane></div></div><table class=header><tr><td class=page><td style="width:90%"><td class=fullscreen><img src="https://rawcdn.githack.com/nextapps-de/spotlight/master/dist/img/maximize.svg"><img src="https://rawcdn.githack.com/nextapps-de/spotlight/master/dist/img/minimize.svg"><td class=autofit><img src="https://rawcdn.githack.com/nextapps-de/spotlight/master/dist/img/autofit.svg"><td class=zoom-out><img src="https://rawcdn.githack.com/nextapps-de/spotlight/master/dist/img/zoom-out.svg"><td class=zoom-in><img src="https://rawcdn.githack.com/nextapps-de/spotlight/master/dist/img/zoom-in.svg"><td class=theme><img src="https://rawcdn.githack.com/nextapps-de/spotlight/master/dist/img/theme.svg"><td class=player><img src="https://rawcdn.githack.com/nextapps-de/spotlight/master/dist/img/play.svg"><img src="https://rawcdn.githack.com/nextapps-de/spotlight/master/dist/img/pause.svg"><td class=close><img src="https://rawcdn.githack.com/nextapps-de/spotlight/master/dist/img/close.svg"></table><div class="arrow arrow-left"><img src="https://rawcdn.githack.com/nextapps-de/spotlight/master/dist/img/arrow.svg"></div><div class="arrow arrow-right"><img src="https://rawcdn.githack.com/nextapps-de/spotlight/master/dist/img/arrow.svg"></div><table class=footer><tr><td class=title><tr><td class=description></table>';k(M,
"transition","none");document.body.appendChild(M);I=l("scene",M)[0];N=l("footer",M)[0];oa=l("title",N)[0];pa=l("description",N)[0];qa=l("arrow-left",M)[0];ra=l("arrow-right",M)[0];O=l("fullscreen",M)[0];sa=l("page",M)[0];P=l("player",M)[0];document.cancelFullScreen||(document.cancelFullScreen=document.exitFullscreen||document.webkitCancelFullScreen||document.webkitExitFullscreen||document.mozCancelFullScreen||function(){});T=document.documentElement||document.body;T.requestFullScreen||(T.requestFullScreen=
T.webkitRequestFullScreen||T.msRequestFullScreen||T.mozRequestFullScreen||k(O,"display","none")||function(){});ta=[[window,"keydown",za],[window,"wheel",Aa],[window,"hashchange",Ba],[I,"mousedown",Ca],[I,"mouseleave",V],[I,"mouseup",V],[I,"mousemove",Da],[I,"touchstart",Ca,{passive:!0}],[I,"touchcancel",V],[I,"touchend",V],[I,"touchmove",Da,{passive:!0}],[O,"",Ea],[qa,"",X],[ra,"",Y],[P,"",Fa],[l("autofit",M)[0],"",Ga],[l("zoom-in",M)[0],"",Ha],[l("zoom-out",M)[0],"",Ia],[l("close",M)[0],"",Ja],[l("theme",
M)[0],"",ya]];fa(window,"",Ka)},{once:!0});function La(a){for(var b=0;b<ta.length;b++){var c=ta[b];(a?ia:fa)(c[0],c[1],c[2],c[3])}}function Ka(a){var b=Ma.call(a.target,".spotlight");if(b){var c=Ma.call(b,".spotlight-group"),d=l("spotlight",c);wa(b.dataset,c&&c.dataset);for(c=0;c<d.length;c++)if(d[c]===b){ua(d,c+1);break}Na();return p(a)}}
function za(a){if(J)switch(a.keyCode){case 8:Ga();break;case 32:"false"!==G.player&&Fa();break;case 37:X();break;case 39:Y();break;case 38:case 107:case 187:Ha();break;case 40:case 109:case 189:Ia()}}function Aa(a){J&&(a=a.deltaY,0>.5*(0>a?1:a?-1:0)?Ia():Ha())}function Ba(){J&&"#spotlight"===location.hash&&Ja(!0)}function Fa(a){("boolean"===typeof a?a:!Q)?Q||(Q=setInterval(Y,1*G.player||5E3),g(P,"on")):Q&&(Q=clearInterval(Q),h(P,"on"));return Q}
function Z(){S?clearTimeout(S):g(M,"menu");var a=G.autohide;S="false"!==a?setTimeout(function(){h(M,"menu");S=null},1*a||2E3):1}function Ca(a){ma=!0;na=!1;var b=Oa(a);u=document.body.clientWidth;v=document.body.clientHeight;w=L.width*y;x=L.height*y;z=w<=u;ka=b.x;la=b.y;return p(a,!0)}function V(a){z&&na&&(ea(I,"transform","translateX("+-(100*(E-1)-r/u*100)+"%)"),r<-(v/5)&&Y()||r>v/5&&X()||k(I,"transform","translateX(-"+100*(E-1)+"%)"),r=0,z=!1,k(J,"transform",""));ma=!1;return p(a)}
function Da(a){if(ma){R||(R=requestAnimationFrame(Pa));var b=Oa(a),c=(w-u)/2;na=!0;z=w<=u;r-=ka-(ka=b.x);z?A=!0:r>c?r=c:0<u-r-w+c?r=u-w+c:A=!0;x>v&&(c=(x-v)/2,t-=la-(la=b.y),t>c?t=c:0<v-t-x+c?t=v-x+c:A=!0)}else Z();return p(a,!0)}function Oa(a){var b=a.touches;b&&(b=b[0]);return{x:b?b.clientX:a.pageX,y:b?b.clientY:a.pageY}}function Pa(a){A?(a&&(R=requestAnimationFrame(Pa)),k(J,"transform","translate("+r+"px, "+t+"px)")):R=null;A=!1}
function Ea(a){(a="boolean"===typeof a?a:document.isFullScreen||document.webkitIsFullScreen||document.mozFullScreen)?(document.cancelFullScreen(),h(O,"on")):(T.requestFullScreen(),g(O,"on"));return!a}function Ga(a){"boolean"===typeof a&&(B=!a);B=1===y&&!B;k(L,{maxHeight:B?"none":"",maxWidth:B?"none":"",transform:""});y=1;t=r=0;A=!0;Pa();Z()}function Ha(a){Qa(y/=.65);a||Z()}function Qa(a){k(L,"transform","translate(-50%, -50%) scale("+(a||1)+")")}
function Ia(a){var b=.65*y;1>b&&(b=1);b!==y&&(Qa(y=b),t=r=0,A=!0,Pa());a||Z()}function Na(){location.hash="spotlight";location.hash="show";La();k(M,"transition","");g(T,"hide-scrollbars");g(M,"show");Z()}function Ja(a){La(!0);history.go(!0===a?-1:-2);h(T,"hide-scrollbars");h(M,"show");Q&&Fa(!1);L.parentNode.removeChild(L);L=J=null}function X(){Q||Z();if(1<E)return E--,U(!1),!0;if(Q||H)return Ra(F)}function Y(){Q||Z();if(E<F)return E++,U(!0),!0;if(Q||H)return Ra(1)}
function Ra(a){if(a!==E){Q||Z();var b=a>E;E=a;U(b);return!0}}function ya(a){"boolean"===typeof a?D=a:(D=!D,Z());D?g(M,"white"):h(M,"white")}
function U(a){t=r=0;y=1;var b=G.animation,c=!0,d=!0,f=!0,e=!1;if("undefined"!==typeof b){e=f=d=c=!1;b=b.split(",");for(var m=0;m<b.length;m++){var n=b[m].trim();"scale"===n?c=!0:"fade"===n?d=!0:"slide"===n?f=!0:"rotate"===n&&(e=!0)}}k(I,"transition",f?"":"none");k(I,"transform","translateX(-"+100*(E-1)+"%)");k(J,"transform","");k(L,{opacity:d?0:1,transform:""});var C=L;setTimeout(function(){C&&L!==C&&C.parentNode&&C.parentNode.removeChild(C)},800);f=va(E);ea(L,{opacity:d?0:1,transform:"translate(-50%, -50%)"+
(c?" scale(0.8)":"")+(e&&"undefined"!==typeof a?" rotateY("+(a?"":"-")+"135deg)":""),maxHeight:"",maxWidth:""});f&&k(L,{opacity:1,transform:""});k(J,"transform","");k(qa,"visibility",H||1!==E?"":"hidden");k(ra,"visibility",H||E!==F?"":"hidden");a=J.dataset;if(c=a.title||a.description)oa.textContent=a.title||"",pa.textContent=a.description||"";k(N,"visibility",c?"visible":"hidden");sa.textContent=E+" / "+F}
var Ma=Element.prototype.closest||function(a){var b=this;for(a=a.substring(1);b&&1===b.nodeType;){if(b.classList.contains(a))return b;b=b.parentNode}};window.Spotlight={theme:ya,fullscreen:Ea,autofit:Ga,next:Y,prev:X,"goto":Ra,close:Ja,zoom:Qa,menu:function(a){"boolean"===typeof a&&(S=a?S:0);S?(S=clearTimeout(S),h(M,"menu")):Z();return p(a)},show:function(a,b){setTimeout(function(){a?(b?wa(b):b={},ua(a,b.index)):G={};Na()})},play:Fa};}).call(this);
